export enum ErrorCode {
    SUCCESS = "SUCCESS",
    EXCEPTION_ERROR = "EXCEPTION_ERROR",
    INPUT_HEADER_NULL = "INPUT_HEADER_NULL",
    INPUT_PARAM_NULL = "INPUT_PARAM_NULL",
    OUTPUT_PARAM_NULL = "OUTPUT_PARAM_NULL",
    PERMISSION_DENIED = "PERMISSION_DENIED",
    FILE_NOT_FOUND = "FILE_NOT_FOUND",
    METHOD_NOT_FOUND = "METHOD_NOT_FOUND",
    TIMEOUT_ERROR = "TIMEOUT_ERROR",
}
